import type { AppLanguage } from './translations';

export type VocabularyTranslation = {
  vocabulary: {
    dictionaries: string;
    dictionariesDescription: string;
    dictionary: string;
    pairDictionary: string;
    pairDictionaryDescription: string;
    openDictionary: string;
    quickAdd: string;
    quickAddDescription: string;
    targetDictionary: string;
    selectPair: string;
    selectTopic: string;
    choosePair: string;
    chooseTopic: string;
    noTopicsForPair: string;
    search: string;
    searchPlaceholder: string;
    all: string;
    uniqueWords: string;
    entries: string;
    languagePairs: string;
    context: string;
    contextDescription: string;
    contextPlaceholder: string;
    encounterSource: string;
    encounterSourceDescription: string;
    encounterSourcePlaceholder: string;
    duplicateTitle: string;
    duplicateDescription: string;
    duplicatePair: string;
    duplicateTopic: string;
    addAnyway: string;
    changeWord: string;
    added: string;
    addedDescription: string;
    addAnother: string;
    noDictionaries: string;
    noDictionariesDescription: string;
    noResults: string;
    noResultsDescription: string;
    learningOnly: string;
    learnedOnly: string;
    translations: string;
    contexts: string;
    foundIn: string;
    backToDictionaries: string;
    wordExists: string;
  };
};

export const vocabularyTranslations: Record<AppLanguage, VocabularyTranslation> = {
  en: { vocabulary: {
    dictionaries: 'Dictionaries', dictionariesDescription: 'Browse your vocabulary by the language you are learning. Pairs with the same target language are combined automatically.', dictionary: 'Dictionary', pairDictionary: 'Pair dictionary', pairDictionaryDescription: 'All words from every topic in this language pair.', openDictionary: 'Open dictionary', quickAdd: 'Quick add', quickAddDescription: 'Save a word without navigating through topics first.', targetDictionary: 'Target dictionary', selectPair: 'Language pair', selectTopic: 'Topic', choosePair: 'Choose a language pair', chooseTopic: 'Choose a topic', noTopicsForPair: 'This language pair has no topics yet.', search: 'Search', searchPlaceholder: 'Search words, translations, meanings or context…', all: 'All', uniqueWords: 'unique words', entries: 'entries', languagePairs: 'language pairs', context: 'Context', contextDescription: 'A sentence or situation that helps you remember how the word was used.', contextPlaceholder: 'Example: The bus was packed this morning.', encounterSource: 'Where you found it', encounterSourceDescription: 'Optional note about where you encountered this word.', encounterSourcePlaceholder: 'Work, a book, Netflix, a conversation…', duplicateTitle: 'You already have this word', duplicateDescription: 'This target-language word already exists in your vocabulary. You can still add it with another translation, meaning or context.', duplicatePair: 'Pair', duplicateTopic: 'Topic', addAnyway: 'Add anyway', changeWord: 'Change word', added: 'Word added', addedDescription: 'Saved to your vocabulary.', addAnother: 'Add another word', noDictionaries: 'No dictionaries yet', noDictionariesDescription: 'Create a language pair to start building a dictionary.', noResults: 'Nothing found', noResultsDescription: 'Try another search or filter.', learningOnly: 'Learning', learnedOnly: 'Learned', translations: 'Translations', contexts: 'Contexts', foundIn: 'Found in', backToDictionaries: 'Back to dictionaries', wordExists: 'Already in vocabulary' } },
  ru: { vocabulary: {
    dictionaries: 'Словари', dictionariesDescription: 'Смотри весь словарный запас по изучаемому языку. Пары с одинаковым целевым языком объединяются автоматически.', dictionary: 'Словарь', pairDictionary: 'Словарь пары', pairDictionaryDescription: 'Все слова из всех тем этой языковой пары.', openDictionary: 'Открыть словарь', quickAdd: 'Быстро добавить', quickAddDescription: 'Сохрани слово без перехода по темам.', targetDictionary: 'Целевой словарь', selectPair: 'Языковая пара', selectTopic: 'Тема', choosePair: 'Выбери языковую пару', chooseTopic: 'Выбери тему', noTopicsForPair: 'В этой языковой паре пока нет тем.', search: 'Поиск', searchPlaceholder: 'Ищи слова, переводы, значения или контекст…', all: 'Все', uniqueWords: 'уникальных слов', entries: 'записей', languagePairs: 'языковых пар', context: 'Контекст', contextDescription: 'Предложение или ситуация, которая помогает вспомнить, как использовалось слово.', contextPlaceholder: 'Например: The bus was packed this morning.', encounterSource: 'Где встретилось', encounterSourceDescription: 'Необязательная заметка о том, где ты встретил это слово.', encounterSourcePlaceholder: 'Работа, книга, Netflix, разговор…', duplicateTitle: 'Такое слово уже есть', duplicateDescription: 'Это слово уже существует в словаре изучаемого языка. Его всё равно можно добавить с другим переводом, значением или контекстом.', duplicatePair: 'Пара', duplicateTopic: 'Тема', addAnyway: 'Всё равно добавить', changeWord: 'Изменить слово', added: 'Слово добавлено', addedDescription: 'Оно сохранено в твоём словаре.', addAnother: 'Добавить ещё слово', noDictionaries: 'Словарей пока нет', noDictionariesDescription: 'Создай языковую пару, чтобы начать собирать словарь.', noResults: 'Ничего не найдено', noResultsDescription: 'Попробуй другой запрос или фильтр.', learningOnly: 'Учу', learnedOnly: 'Выучено', translations: 'Переводы', contexts: 'Контексты', foundIn: 'Встречается в', backToDictionaries: 'Назад к словарям', wordExists: 'Уже есть в словаре' } },
  uk: { vocabulary: {
    dictionaries: 'Словники', dictionariesDescription: 'Переглядай словниковий запас за мовою, яку вивчаєш. Пари з однаковою цільовою мовою об’єднуються автоматично.', dictionary: 'Словник', pairDictionary: 'Словник пари', pairDictionaryDescription: 'Усі слова з усіх тем цієї мовної пари.', openDictionary: 'Відкрити словник', quickAdd: 'Швидко додати', quickAddDescription: 'Збережи слово без переходу по темах.', targetDictionary: 'Цільовий словник', selectPair: 'Мовна пара', selectTopic: 'Тема', choosePair: 'Обери мовну пару', chooseTopic: 'Обери тему', noTopicsForPair: 'У цій мовній парі ще немає тем.', search: 'Пошук', searchPlaceholder: 'Шукай слова, переклади, значення або контекст…', all: 'Усі', uniqueWords: 'унікальних слів', entries: 'записів', languagePairs: 'мовних пар', context: 'Контекст', contextDescription: 'Речення або ситуація, що допомагає згадати, як уживалося слово.', contextPlaceholder: 'Наприклад: The bus was packed this morning.', encounterSource: 'Де зустрілося', encounterSourceDescription: 'Необов’язкова нотатка про те, де ти зустрів це слово.', encounterSourcePlaceholder: 'Робота, книга, Netflix, розмова…', duplicateTitle: 'Таке слово вже є', duplicateDescription: 'Це слово вже є у словнику цільової мови. Його все одно можна додати з іншим перекладом, значенням або контекстом.', duplicatePair: 'Пара', duplicateTopic: 'Тема', addAnyway: 'Усе одно додати', changeWord: 'Змінити слово', added: 'Слово додано', addedDescription: 'Його збережено у твоєму словнику.', addAnother: 'Додати ще слово', noDictionaries: 'Словників ще немає', noDictionariesDescription: 'Створи мовну пару, щоб почати збирати словник.', noResults: 'Нічого не знайдено', noResultsDescription: 'Спробуй інший запит або фільтр.', learningOnly: 'Вивчаю', learnedOnly: 'Вивчено', translations: 'Переклади', contexts: 'Контексти', foundIn: 'Зустрічається в', backToDictionaries: 'Назад до словників', wordExists: 'Вже є у словнику' } },
  de: { vocabulary: {
    dictionaries: 'Wörterbücher', dictionariesDescription: 'Durchsuche deinen Wortschatz nach Zielsprache. Sprachpaare mit derselben Zielsprache werden automatisch zusammengeführt.', dictionary: 'Wörterbuch', pairDictionary: 'Paar-Wörterbuch', pairDictionaryDescription: 'Alle Wörter aus allen Themen dieses Sprachpaars.', openDictionary: 'Wörterbuch öffnen', quickAdd: 'Schnell hinzufügen', quickAddDescription: 'Speichere ein Wort, ohne zuerst durch Themen zu navigieren.', targetDictionary: 'Zielwörterbuch', selectPair: 'Sprachpaar', selectTopic: 'Thema', choosePair: 'Sprachpaar wählen', chooseTopic: 'Thema wählen', noTopicsForPair: 'Dieses Sprachpaar hat noch keine Themen.', search: 'Suchen', searchPlaceholder: 'Wörter, Übersetzungen, Bedeutungen oder Kontext suchen…', all: 'Alle', uniqueWords: 'eindeutige Wörter', entries: 'Einträge', languagePairs: 'Sprachpaare', context: 'Kontext', contextDescription: 'Ein Satz oder eine Situation, die dir hilft, die Verwendung des Wortes zu erinnern.', contextPlaceholder: 'Beispiel: The bus was packed this morning.', encounterSource: 'Wo gefunden', encounterSourceDescription: 'Optionale Notiz dazu, wo dir dieses Wort begegnet ist.', encounterSourcePlaceholder: 'Arbeit, Buch, Netflix, Gespräch…', duplicateTitle: 'Dieses Wort gibt es bereits', duplicateDescription: 'Dieses Wort existiert bereits in deinem Zielsprachen-Wörterbuch. Du kannst es trotzdem mit einer anderen Übersetzung, Bedeutung oder einem anderen Kontext hinzufügen.', duplicatePair: 'Paar', duplicateTopic: 'Thema', addAnyway: 'Trotzdem hinzufügen', changeWord: 'Wort ändern', added: 'Wort hinzugefügt', addedDescription: 'In deinem Wörterbuch gespeichert.', addAnother: 'Weiteres Wort hinzufügen', noDictionaries: 'Noch keine Wörterbücher', noDictionariesDescription: 'Erstelle ein Sprachpaar, um dein erstes Wörterbuch aufzubauen.', noResults: 'Nichts gefunden', noResultsDescription: 'Versuche eine andere Suche oder einen anderen Filter.', learningOnly: 'Lernen', learnedOnly: 'Gelernt', translations: 'Übersetzungen', contexts: 'Kontexte', foundIn: 'Gefunden in', backToDictionaries: 'Zurück zu Wörterbüchern', wordExists: 'Bereits im Wörterbuch' } },
  es: { vocabulary: {
    dictionaries: 'Diccionarios', dictionariesDescription: 'Explora tu vocabulario por el idioma que estás aprendiendo. Los pares con el mismo idioma de destino se combinan automáticamente.', dictionary: 'Diccionario', pairDictionary: 'Diccionario del par', pairDictionaryDescription: 'Todas las palabras de todos los temas de este par de idiomas.', openDictionary: 'Abrir diccionario', quickAdd: 'Añadir rápido', quickAddDescription: 'Guarda una palabra sin navegar primero por los temas.', targetDictionary: 'Diccionario de destino', selectPair: 'Par de idiomas', selectTopic: 'Tema', choosePair: 'Elige un par de idiomas', chooseTopic: 'Elige un tema', noTopicsForPair: 'Este par de idiomas todavía no tiene temas.', search: 'Buscar', searchPlaceholder: 'Busca palabras, traducciones, significados o contexto…', all: 'Todas', uniqueWords: 'palabras únicas', entries: 'entradas', languagePairs: 'pares de idiomas', context: 'Contexto', contextDescription: 'Una frase o situación que te ayude a recordar cómo se usó la palabra.', contextPlaceholder: 'Ejemplo: The bus was packed this morning.', encounterSource: 'Dónde la encontraste', encounterSourceDescription: 'Nota opcional sobre dónde encontraste esta palabra.', encounterSourcePlaceholder: 'Trabajo, un libro, Netflix, una conversación…', duplicateTitle: 'Ya tienes esta palabra', duplicateDescription: 'Esta palabra ya existe en tu diccionario del idioma de destino. Aun así puedes añadirla con otra traducción, significado o contexto.', duplicatePair: 'Par', duplicateTopic: 'Tema', addAnyway: 'Añadir de todos modos', changeWord: 'Cambiar palabra', added: 'Palabra añadida', addedDescription: 'Guardada en tu diccionario.', addAnother: 'Añadir otra palabra', noDictionaries: 'Aún no hay diccionarios', noDictionariesDescription: 'Crea un par de idiomas para empezar a construir un diccionario.', noResults: 'No se encontró nada', noResultsDescription: 'Prueba otra búsqueda o filtro.', learningOnly: 'Aprendiendo', learnedOnly: 'Aprendidas', translations: 'Traducciones', contexts: 'Contextos', foundIn: 'Encontrada en', backToDictionaries: 'Volver a diccionarios', wordExists: 'Ya está en el diccionario' } },
  fr: { vocabulary: {
    dictionaries: 'Dictionnaires', dictionariesDescription: 'Parcourez votre vocabulaire par langue cible. Les paires ayant la même langue cible sont regroupées automatiquement.', dictionary: 'Dictionnaire', pairDictionary: 'Dictionnaire de la paire', pairDictionaryDescription: 'Tous les mots de tous les thèmes de cette paire de langues.', openDictionary: 'Ouvrir le dictionnaire', quickAdd: 'Ajout rapide', quickAddDescription: 'Enregistrez un mot sans parcourir les thèmes.', targetDictionary: 'Dictionnaire cible', selectPair: 'Paire de langues', selectTopic: 'Thème', choosePair: 'Choisissez une paire de langues', chooseTopic: 'Choisissez un thème', noTopicsForPair: 'Cette paire de langues ne contient encore aucun thème.', search: 'Rechercher', searchPlaceholder: 'Rechercher des mots, traductions, sens ou contextes…', all: 'Tous', uniqueWords: 'mots uniques', entries: 'entrées', languagePairs: 'paires de langues', context: 'Contexte', contextDescription: 'Une phrase ou une situation qui vous aide à vous souvenir de l’utilisation du mot.', contextPlaceholder: 'Exemple : The bus was packed this morning.', encounterSource: 'Où vous l’avez trouvé', encounterSourceDescription: 'Note facultative indiquant où vous avez rencontré ce mot.', encounterSourcePlaceholder: 'Travail, livre, Netflix, conversation…', duplicateTitle: 'Ce mot existe déjà', duplicateDescription: 'Ce mot existe déjà dans votre dictionnaire de langue cible. Vous pouvez tout de même l’ajouter avec une autre traduction, un autre sens ou contexte.', duplicatePair: 'Paire', duplicateTopic: 'Thème', addAnyway: 'Ajouter quand même', changeWord: 'Modifier le mot', added: 'Mot ajouté', addedDescription: 'Enregistré dans votre dictionnaire.', addAnother: 'Ajouter un autre mot', noDictionaries: 'Aucun dictionnaire', noDictionariesDescription: 'Créez une paire de langues pour commencer un dictionnaire.', noResults: 'Aucun résultat', noResultsDescription: 'Essayez une autre recherche ou un autre filtre.', learningOnly: 'En cours', learnedOnly: 'Appris', translations: 'Traductions', contexts: 'Contextes', foundIn: 'Trouvé dans', backToDictionaries: 'Retour aux dictionnaires', wordExists: 'Déjà dans le dictionnaire' } },
  it: { vocabulary: {
    dictionaries: 'Dizionari', dictionariesDescription: 'Esplora il tuo vocabolario per lingua di destinazione. Le coppie con la stessa lingua di destinazione vengono unite automaticamente.', dictionary: 'Dizionario', pairDictionary: 'Dizionario della coppia', pairDictionaryDescription: 'Tutte le parole di tutti gli argomenti di questa coppia linguistica.', openDictionary: 'Apri dizionario', quickAdd: 'Aggiunta rapida', quickAddDescription: 'Salva una parola senza navigare prima tra gli argomenti.', targetDictionary: 'Dizionario di destinazione', selectPair: 'Coppia linguistica', selectTopic: 'Argomento', choosePair: 'Scegli una coppia linguistica', chooseTopic: 'Scegli un argomento', noTopicsForPair: 'Questa coppia linguistica non ha ancora argomenti.', search: 'Cerca', searchPlaceholder: 'Cerca parole, traduzioni, significati o contesto…', all: 'Tutte', uniqueWords: 'parole uniche', entries: 'voci', languagePairs: 'coppie linguistiche', context: 'Contesto', contextDescription: 'Una frase o situazione che ti aiuta a ricordare come è stata usata la parola.', contextPlaceholder: 'Esempio: The bus was packed this morning.', encounterSource: 'Dove l’hai trovata', encounterSourceDescription: 'Nota facoltativa su dove hai incontrato questa parola.', encounterSourcePlaceholder: 'Lavoro, libro, Netflix, conversazione…', duplicateTitle: 'Hai già questa parola', duplicateDescription: 'Questa parola esiste già nel dizionario della lingua di destinazione. Puoi comunque aggiungerla con un’altra traduzione, significato o contesto.', duplicatePair: 'Coppia', duplicateTopic: 'Argomento', addAnyway: 'Aggiungi comunque', changeWord: 'Cambia parola', added: 'Parola aggiunta', addedDescription: 'Salvata nel tuo dizionario.', addAnother: 'Aggiungi un’altra parola', noDictionaries: 'Nessun dizionario', noDictionariesDescription: 'Crea una coppia linguistica per iniziare a costruire un dizionario.', noResults: 'Nessun risultato', noResultsDescription: 'Prova un’altra ricerca o filtro.', learningOnly: 'In apprendimento', learnedOnly: 'Imparate', translations: 'Traduzioni', contexts: 'Contesti', foundIn: 'Trovata in', backToDictionaries: 'Torna ai dizionari', wordExists: 'Già nel dizionario' } },
  pt: { vocabulary: {
    dictionaries: 'Dicionários', dictionariesDescription: 'Explore seu vocabulário pelo idioma que está aprendendo. Pares com o mesmo idioma de destino são combinados automaticamente.', dictionary: 'Dicionário', pairDictionary: 'Dicionário do par', pairDictionaryDescription: 'Todas as palavras de todos os tópicos deste par de idiomas.', openDictionary: 'Abrir dicionário', quickAdd: 'Adicionar rápido', quickAddDescription: 'Salve uma palavra sem navegar primeiro pelos tópicos.', targetDictionary: 'Dicionário de destino', selectPair: 'Par de idiomas', selectTopic: 'Tópico', choosePair: 'Escolha um par de idiomas', chooseTopic: 'Escolha um tópico', noTopicsForPair: 'Este par de idiomas ainda não tem tópicos.', search: 'Pesquisar', searchPlaceholder: 'Pesquise palavras, traduções, significados ou contexto…', all: 'Todas', uniqueWords: 'palavras únicas', entries: 'entradas', languagePairs: 'pares de idiomas', context: 'Contexto', contextDescription: 'Uma frase ou situação que ajuda você a lembrar como a palavra foi usada.', contextPlaceholder: 'Exemplo: The bus was packed this morning.', encounterSource: 'Onde você encontrou', encounterSourceDescription: 'Nota opcional sobre onde você encontrou esta palavra.', encounterSourcePlaceholder: 'Trabalho, livro, Netflix, conversa…', duplicateTitle: 'Você já tem esta palavra', duplicateDescription: 'Esta palavra já existe no dicionário do idioma de destino. Você ainda pode adicioná-la com outra tradução, significado ou contexto.', duplicatePair: 'Par', duplicateTopic: 'Tópico', addAnyway: 'Adicionar mesmo assim', changeWord: 'Alterar palavra', added: 'Palavra adicionada', addedDescription: 'Salva no seu dicionário.', addAnother: 'Adicionar outra palavra', noDictionaries: 'Nenhum dicionário ainda', noDictionariesDescription: 'Crie um par de idiomas para começar a construir um dicionário.', noResults: 'Nada encontrado', noResultsDescription: 'Tente outra pesquisa ou filtro.', learningOnly: 'Aprendendo', learnedOnly: 'Aprendidas', translations: 'Traduções', contexts: 'Contextos', foundIn: 'Encontrada em', backToDictionaries: 'Voltar aos dicionários', wordExists: 'Já está no dicionário' } },
  pl: { vocabulary: {
    dictionaries: 'Słowniki', dictionariesDescription: 'Przeglądaj słownictwo według języka docelowego. Pary z tym samym językiem docelowym są automatycznie łączone.', dictionary: 'Słownik', pairDictionary: 'Słownik pary', pairDictionaryDescription: 'Wszystkie słowa ze wszystkich tematów tej pary językowej.', openDictionary: 'Otwórz słownik', quickAdd: 'Szybkie dodawanie', quickAddDescription: 'Zapisz słowo bez wcześniejszego przechodzenia przez tematy.', targetDictionary: 'Słownik docelowy', selectPair: 'Para językowa', selectTopic: 'Temat', choosePair: 'Wybierz parę językową', chooseTopic: 'Wybierz temat', noTopicsForPair: 'Ta para językowa nie ma jeszcze tematów.', search: 'Szukaj', searchPlaceholder: 'Szukaj słów, tłumaczeń, znaczeń lub kontekstu…', all: 'Wszystkie', uniqueWords: 'unikalnych słów', entries: 'wpisów', languagePairs: 'par językowych', context: 'Kontekst', contextDescription: 'Zdanie lub sytuacja, która pomaga zapamiętać użycie słowa.', contextPlaceholder: 'Przykład: The bus was packed this morning.', encounterSource: 'Gdzie je znalazłeś', encounterSourceDescription: 'Opcjonalna notatka o tym, gdzie spotkałeś to słowo.', encounterSourcePlaceholder: 'Praca, książka, Netflix, rozmowa…', duplicateTitle: 'Masz już to słowo', duplicateDescription: 'To słowo już istnieje w słowniku języka docelowego. Nadal możesz je dodać z innym tłumaczeniem, znaczeniem lub kontekstem.', duplicatePair: 'Para', duplicateTopic: 'Temat', addAnyway: 'Dodaj mimo to', changeWord: 'Zmień słowo', added: 'Słowo dodane', addedDescription: 'Zapisano w twoim słowniku.', addAnother: 'Dodaj kolejne słowo', noDictionaries: 'Brak słowników', noDictionariesDescription: 'Utwórz parę językową, aby zacząć budować słownik.', noResults: 'Nic nie znaleziono', noResultsDescription: 'Spróbuj innego wyszukiwania lub filtra.', learningOnly: 'W nauce', learnedOnly: 'Nauczone', translations: 'Tłumaczenia', contexts: 'Konteksty', foundIn: 'Znaleziono w', backToDictionaries: 'Wróć do słowników', wordExists: 'Już w słowniku' } },
  tr: { vocabulary: {
    dictionaries: 'Sözlükler', dictionariesDescription: 'Kelime dağarcığını öğrendiğin hedef dile göre görüntüle. Aynı hedef dile sahip dil çiftleri otomatik olarak birleştirilir.', dictionary: 'Sözlük', pairDictionary: 'Çift sözlüğü', pairDictionaryDescription: 'Bu dil çiftindeki tüm konuların bütün kelimeleri.', openDictionary: 'Sözlüğü aç', quickAdd: 'Hızlı ekle', quickAddDescription: 'Konular arasında gezinmeden bir kelime kaydet.', targetDictionary: 'Hedef sözlük', selectPair: 'Dil çifti', selectTopic: 'Konu', choosePair: 'Bir dil çifti seç', chooseTopic: 'Bir konu seç', noTopicsForPair: 'Bu dil çiftinde henüz konu yok.', search: 'Ara', searchPlaceholder: 'Kelime, çeviri, anlam veya bağlam ara…', all: 'Tümü', uniqueWords: 'benzersiz kelime', entries: 'kayıt', languagePairs: 'dil çifti', context: 'Bağlam', contextDescription: 'Kelimenin nasıl kullanıldığını hatırlamana yardımcı olan cümle veya durum.', contextPlaceholder: 'Örnek: The bus was packed this morning.', encounterSource: 'Nerede karşılaştın', encounterSourceDescription: 'Bu kelimeyle nerede karşılaştığına dair isteğe bağlı not.', encounterSourcePlaceholder: 'İş, kitap, Netflix, sohbet…', duplicateTitle: 'Bu kelime zaten var', duplicateDescription: 'Bu hedef dil kelimesi sözlüğünde zaten mevcut. Yine de farklı bir çeviri, anlam veya bağlamla ekleyebilirsin.', duplicatePair: 'Çift', duplicateTopic: 'Konu', addAnyway: 'Yine de ekle', changeWord: 'Kelimeyi değiştir', added: 'Kelime eklendi', addedDescription: 'Sözlüğüne kaydedildi.', addAnother: 'Başka kelime ekle', noDictionaries: 'Henüz sözlük yok', noDictionariesDescription: 'Bir sözlük oluşturmaya başlamak için dil çifti oluştur.', noResults: 'Sonuç bulunamadı', noResultsDescription: 'Başka bir arama veya filtre dene.', learningOnly: 'Öğreniliyor', learnedOnly: 'Öğrenildi', translations: 'Çeviriler', contexts: 'Bağlamlar', foundIn: 'Bulunduğu yer', backToDictionaries: 'Sözlüklere dön', wordExists: 'Zaten sözlükte' } },
  zh: { vocabulary: {
    dictionaries: '词典', dictionariesDescription: '按你正在学习的目标语言浏览词汇。目标语言相同的语言对会自动合并。', dictionary: '词典', pairDictionary: '语言对词典', pairDictionaryDescription: '这个语言对中所有主题里的全部单词。', openDictionary: '打开词典', quickAdd: '快速添加', quickAddDescription: '无需先进入主题即可保存单词。', targetDictionary: '目标词典', selectPair: '语言对', selectTopic: '主题', choosePair: '选择语言对', chooseTopic: '选择主题', noTopicsForPair: '这个语言对还没有主题。', search: '搜索', searchPlaceholder: '搜索单词、翻译、含义或上下文…', all: '全部', uniqueWords: '个唯一单词', entries: '条记录', languagePairs: '个语言对', context: '上下文', contextDescription: '帮助你记住这个词如何使用的句子或情境。', contextPlaceholder: '例如：The bus was packed this morning.', encounterSource: '在哪里遇到', encounterSourceDescription: '可选：记录你在哪里遇到这个词。', encounterSourcePlaceholder: '工作、书籍、Netflix、对话…', duplicateTitle: '这个词已经存在', duplicateDescription: '这个目标语言单词已经在你的词典中。你仍然可以用不同翻译、含义或上下文再次添加。', duplicatePair: '语言对', duplicateTopic: '主题', addAnyway: '仍然添加', changeWord: '修改单词', added: '已添加单词', addedDescription: '已保存到你的词典。', addAnother: '再添加一个', noDictionaries: '还没有词典', noDictionariesDescription: '创建语言对开始建立词典。', noResults: '没有找到结果', noResultsDescription: '试试其他搜索或筛选。', learningOnly: '学习中', learnedOnly: '已学会', translations: '翻译', contexts: '上下文', foundIn: '出现于', backToDictionaries: '返回词典', wordExists: '已在词典中' } },
  ja: { vocabulary: {
    dictionaries: '辞書', dictionariesDescription: '学習中の対象言語ごとに語彙を確認できます。同じ対象言語の言語ペアは自動的に統合されます。', dictionary: '辞書', pairDictionary: 'ペア辞書', pairDictionaryDescription: 'この言語ペアのすべてのトピックにある単語。', openDictionary: '辞書を開く', quickAdd: 'クイック追加', quickAddDescription: 'トピックをたどらずに単語を保存します。', targetDictionary: '対象言語の辞書', selectPair: '言語ペア', selectTopic: 'トピック', choosePair: '言語ペアを選択', chooseTopic: 'トピックを選択', noTopicsForPair: 'この言語ペアにはまだトピックがありません。', search: '検索', searchPlaceholder: '単語、翻訳、意味、文脈を検索…', all: 'すべて', uniqueWords: '語', entries: '件', languagePairs: '言語ペア', context: '文脈', contextDescription: 'その単語がどのように使われたか思い出すための文や状況。', contextPlaceholder: '例: The bus was packed this morning.', encounterSource: 'どこで見つけたか', encounterSourceDescription: 'この単語に出会った場所についての任意メモ。', encounterSourcePlaceholder: '仕事、本、Netflix、会話…', duplicateTitle: 'この単語はすでにあります', duplicateDescription: 'この対象言語の単語はすでに辞書にあります。別の翻訳、意味、文脈で追加することもできます。', duplicatePair: 'ペア', duplicateTopic: 'トピック', addAnyway: 'それでも追加', changeWord: '単語を変更', added: '単語を追加しました', addedDescription: '辞書に保存しました。', addAnother: '別の単語を追加', noDictionaries: '辞書はまだありません', noDictionariesDescription: '言語ペアを作成して辞書を作り始めましょう。', noResults: '見つかりませんでした', noResultsDescription: '別の検索語やフィルターを試してください。', learningOnly: '学習中', learnedOnly: '学習済み', translations: '翻訳', contexts: '文脈', foundIn: '登録場所', backToDictionaries: '辞書に戻る', wordExists: '辞書に登録済み' } },
  ko: { vocabulary: {
    dictionaries: '사전', dictionariesDescription: '학습 중인 대상 언어별로 어휘를 확인하세요. 대상 언어가 같은 언어 쌍은 자동으로 합쳐집니다.', dictionary: '사전', pairDictionary: '언어 쌍 사전', pairDictionaryDescription: '이 언어 쌍의 모든 주제에 있는 단어입니다.', openDictionary: '사전 열기', quickAdd: '빠른 추가', quickAddDescription: '주제를 먼저 찾아가지 않고 단어를 저장하세요.', targetDictionary: '대상 언어 사전', selectPair: '언어 쌍', selectTopic: '주제', choosePair: '언어 쌍 선택', chooseTopic: '주제 선택', noTopicsForPair: '이 언어 쌍에는 아직 주제가 없습니다.', search: '검색', searchPlaceholder: '단어, 번역, 의미 또는 문맥 검색…', all: '전체', uniqueWords: '개의 고유 단어', entries: '개 항목', languagePairs: '개 언어 쌍', context: '문맥', contextDescription: '단어가 어떻게 사용되었는지 기억하는 데 도움이 되는 문장이나 상황입니다.', contextPlaceholder: '예: The bus was packed this morning.', encounterSource: '어디서 만났나요', encounterSourceDescription: '이 단어를 어디서 접했는지에 대한 선택 메모입니다.', encounterSourcePlaceholder: '직장, 책, Netflix, 대화…', duplicateTitle: '이미 있는 단어입니다', duplicateDescription: '이 대상 언어 단어는 이미 사전에 있습니다. 다른 번역, 의미 또는 문맥으로 계속 추가할 수 있습니다.', duplicatePair: '언어 쌍', duplicateTopic: '주제', addAnyway: '그래도 추가', changeWord: '단어 변경', added: '단어 추가됨', addedDescription: '사전에 저장되었습니다.', addAnother: '다른 단어 추가', noDictionaries: '아직 사전이 없습니다', noDictionariesDescription: '언어 쌍을 만들어 사전을 시작하세요.', noResults: '검색 결과 없음', noResultsDescription: '다른 검색어나 필터를 사용해 보세요.', learningOnly: '학습 중', learnedOnly: '학습 완료', translations: '번역', contexts: '문맥', foundIn: '등록 위치', backToDictionaries: '사전으로 돌아가기', wordExists: '이미 사전에 있음' } },
  ar: { vocabulary: {
    dictionaries: 'القواميس', dictionariesDescription: 'تصفح مفرداتك حسب اللغة التي تتعلمها. يتم دمج أزواج اللغات التي لها نفس اللغة الهدف تلقائيًا.', dictionary: 'القاموس', pairDictionary: 'قاموس الزوج', pairDictionaryDescription: 'كل الكلمات من جميع موضوعات زوج اللغات هذا.', openDictionary: 'فتح القاموس', quickAdd: 'إضافة سريعة', quickAddDescription: 'احفظ كلمة دون التنقل بين الموضوعات أولًا.', targetDictionary: 'قاموس اللغة الهدف', selectPair: 'زوج اللغات', selectTopic: 'الموضوع', choosePair: 'اختر زوج لغات', chooseTopic: 'اختر موضوعًا', noTopicsForPair: 'لا توجد موضوعات في زوج اللغات هذا بعد.', search: 'بحث', searchPlaceholder: 'ابحث عن كلمات أو ترجمات أو معانٍ أو سياق…', all: 'الكل', uniqueWords: 'كلمات فريدة', entries: 'إدخالات', languagePairs: 'أزواج لغات', context: 'السياق', contextDescription: 'جملة أو موقف يساعدك على تذكر طريقة استخدام الكلمة.', contextPlaceholder: 'مثال: The bus was packed this morning.', encounterSource: 'أين وجدتها', encounterSourceDescription: 'ملاحظة اختيارية عن المكان الذي صادفت فيه هذه الكلمة.', encounterSourcePlaceholder: 'العمل، كتاب، Netflix، محادثة…', duplicateTitle: 'هذه الكلمة موجودة بالفعل', duplicateDescription: 'هذه الكلمة موجودة بالفعل في قاموس اللغة الهدف. لا يزال بإمكانك إضافتها بترجمة أو معنى أو سياق مختلف.', duplicatePair: 'الزوج', duplicateTopic: 'الموضوع', addAnyway: 'إضافة على أي حال', changeWord: 'تغيير الكلمة', added: 'تمت إضافة الكلمة', addedDescription: 'تم حفظها في قاموسك.', addAnother: 'إضافة كلمة أخرى', noDictionaries: 'لا توجد قواميس بعد', noDictionariesDescription: 'أنشئ زوج لغات لبدء بناء قاموس.', noResults: 'لا توجد نتائج', noResultsDescription: 'جرّب بحثًا أو فلترًا آخر.', learningOnly: 'قيد التعلم', learnedOnly: 'تم تعلمها', translations: 'الترجمات', contexts: 'السياقات', foundIn: 'موجودة في', backToDictionaries: 'العودة إلى القواميس', wordExists: 'موجودة في القاموس' } },
  hi: { vocabulary: {
    dictionaries: 'शब्दकोश', dictionariesDescription: 'जिस लक्ष्य भाषा को आप सीख रहे हैं उसके अनुसार अपनी शब्दावली देखें। एक ही लक्ष्य भाषा वाले भाषा जोड़े अपने आप जुड़ जाते हैं।', dictionary: 'शब्दकोश', pairDictionary: 'जोड़ी शब्दकोश', pairDictionaryDescription: 'इस भाषा जोड़ी के सभी विषयों के सभी शब्द।', openDictionary: 'शब्दकोश खोलें', quickAdd: 'जल्दी जोड़ें', quickAddDescription: 'पहले विषयों में जाए बिना कोई शब्द सेव करें।', targetDictionary: 'लक्ष्य शब्दकोश', selectPair: 'भाषा जोड़ी', selectTopic: 'विषय', choosePair: 'भाषा जोड़ी चुनें', chooseTopic: 'विषय चुनें', noTopicsForPair: 'इस भाषा जोड़ी में अभी कोई विषय नहीं है।', search: 'खोजें', searchPlaceholder: 'शब्द, अनुवाद, अर्थ या संदर्भ खोजें…', all: 'सभी', uniqueWords: 'अनोखे शब्द', entries: 'प्रविष्टियाँ', languagePairs: 'भाषा जोड़ियाँ', context: 'संदर्भ', contextDescription: 'वह वाक्य या स्थिति जो याद दिलाती है कि शब्द का उपयोग कैसे हुआ था।', contextPlaceholder: 'उदाहरण: The bus was packed this morning.', encounterSource: 'कहाँ मिला', encounterSourceDescription: 'यह शब्द आपको कहाँ मिला, उसकी वैकल्पिक टिप्पणी।', encounterSourcePlaceholder: 'काम, किताब, Netflix, बातचीत…', duplicateTitle: 'यह शब्द पहले से मौजूद है', duplicateDescription: 'यह लक्ष्य-भाषा शब्द आपके शब्दकोश में पहले से है। आप इसे अलग अनुवाद, अर्थ या संदर्भ के साथ फिर भी जोड़ सकते हैं।', duplicatePair: 'जोड़ी', duplicateTopic: 'विषय', addAnyway: 'फिर भी जोड़ें', changeWord: 'शब्द बदलें', added: 'शब्द जोड़ दिया गया', addedDescription: 'आपके शब्दकोश में सेव किया गया।', addAnother: 'एक और शब्द जोड़ें', noDictionaries: 'अभी कोई शब्दकोश नहीं', noDictionariesDescription: 'शब्दकोश बनाना शुरू करने के लिए भाषा जोड़ी बनाएँ।', noResults: 'कुछ नहीं मिला', noResultsDescription: 'दूसरी खोज या फ़िल्टर आज़माएँ।', learningOnly: 'सीख रहे हैं', learnedOnly: 'सीखा हुआ', translations: 'अनुवाद', contexts: 'संदर्भ', foundIn: 'यहाँ मिला', backToDictionaries: 'शब्दकोश पर वापस', wordExists: 'शब्दकोश में पहले से है' } },
};
